# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 50 # it will paginate after this number
language: 'fr-fr'
words_per_minute: 120

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: "/"

# Website info
title: Liberty-Tree
description: Toute ressemblance avec la réalité devra être imputée à cette dernière.
cover: content/images/size/w2000/2016/07/Z6cec4txgkyaHi3ZVmhH0g_0_0.jpg
logo: content/images/2021/12/logo-lt-full-1.png
logo_dark: content/images/2021/12/logo-lt-full-1.png
favicon: assets/images/favicon.png
CNAME: liberty-tree.net

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,

# Disqus
disqus: False
disqus_shortname: jekyllt # replace with your disqus username

# Google Analytics
google_analytics: UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:year/:month/:day/:title/

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-redirect-from]

feed:
  path: feed.xml

collections:
  authors:
    output: true
    permalink: /author/:title/
  pages:
    output: true
    permalink: /:title/
  tags:
    output: true
    permalink: /tag/:title/


defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag
  -
    scope:
      path: ""
      type: posts
    values:
      layout: article
